### ISSUE TITLE
Once it hits the end block make it stay alive and keep resyncing head

### ISSUE THREAD

**Issue by joshstevens19** [joshstevens19/reth-indexer#10]
right now once the code reaches the end block it will exit but we should add a setting in the config like "stayResynced" so once it reaches the top of the head it keeps reindexing the data as it comes in, not a big change just factoring in a delay sleep instead of continue in the while and resetting the from and to parameters

**Comment by halljson** [comment]
would be interesting to include a socket.io connection that broadcasts to a room by event type or contract address
this would enable streaming mined events to a client
I think this would only be needed on new header updates

**Comment by joshstevens19** [comment]
closing as done polling for now which works fine and will be stable.. websocket for sure we can think if we need it but this approach above as low level as you can get
