### ISSUE TITLE
Make it easier to reproduce results

### ISSUE THREAD

**Issue by tjayrush** [joshstevens19/reth-indexer#11]
First, great project. Very interested.

I was hoping to reproduce these results, but I found it difficult to understand exactly what was being indexed (specifically which addresses), what topics (although I guess I understand that it was ERC20 token Transfer and Approval events), and which block range (this was easy).

In the README section about benchmarks, perhaps you could include that information more explicitly in a table so that others can try to reproduce the results themselves on local machines.

Just an idea. Thanks for the great project.

**Comment by joshstevens19** [comment]
hey hey! create idea i did include the from and to and events but someone constructing the mapping json may not know il put a sample in so people can copy and paste out thanks for the idea

**Comment by joshstevens19** [comment]
https://github.com/joshstevens19/reth-indexer/commit/c31aebadbf23bfe9b0d955c81dc953d3244f61a1

done thanks
