### ISSUE TITLE
Use reth-provider over reth-db directly

### ISSUE THREAD

**Issue by joshstevens19** [joshstevens19/reth-indexer#12]

**Comment by joshstevens19** [comment]
am working on this one

**Comment by mattsse** [comment]
please share any pain points you're encountering, working on making this more ergonomic

**Comment by joshstevens19** [comment]
have sent you a DM on telegram have done the change but its 2 minutes slower then direct access to db can share changes in PR if you want

**Comment by joshstevens19** [comment]
https://github.com/joshstevens19/reth-indexer/pull/15

**Comment by joshstevens19** [comment]
https://github.com/joshstevens19/reth-indexer/pull/24
