### ISSUE TITLE
add option to get latest events from api first

### ISSUE THREAD

**Issue by halljson** [joshstevens19/reth-indexer#25]
could include a URL flag `latest=true` to reverse order the timestamps here:

https://github.com/joshstevens19/reth-indexer/blob/master/src/api.rs#L275

**Comment by joshstevens19** [comment]
Hey thanks for this - Yeah I need to fix dates tbh it needs to save as a proper date in postgres and also yes ordering between asc and desc but also between ranges

**Comment by joshstevens19** [comment]
feat added - https://github.com/joshstevens19/reth-indexer/commit/4d38bfb8b8435965d698d21153d136b3f64aab16
