### ISSUE TITLE
Streaming block updates not getting new headers

### ISSUE THREAD

**Issue by halljson** [joshstevens19/reth-indexer#31]
After a full sync, I'm seeing this output on repeat:
```
latest block number: 17678866
last seen block number: 17678867
...
latest block number: 17678866
last seen block number: 17678867
```
It appears that this line is not getting new headers:
https://github.com/joshstevens19/reth-indexer/blob/master/src/indexer.rs#L231-L233

My reth node is definitely syncing new blocks:

```
# curl localhost:8545 -X POST -H "Content-Type: application/json" --data '{"method":"eth_blockNumber","params":["latest",false],"id":1,"jsonrpc":"2.0"}' | jq
{
  "jsonrpc": "2.0",
  "result": "0x10ddca3",
  "id": 1
}
# curl localhost:8545 -X POST -H "Content-Type: application/json" --data '{"method":"eth_blockNumber","params":["latest",false],"id":1,"jsonrpc":"2.0"}' | jq
{
  "jsonrpc": "2.0",
  "result": "0x10ddca4", <-- updated
  "id": 1
}
```

**Comment by joshstevens19** [comment]
Nice ok let me fix this for you again in morning as I am AFK right now! Thanks for testing and raising these things

**Comment by halljson** [comment]
Thank you, I'm trying to debug them as I go but I am brand new to rust. Hopefully I can get up to speed and get some contributions in.

**Comment by joshstevens19** [comment]
All good thanks for testing

**Comment by joshstevens19** [comment]
cant spot this error from scanning need to look a bit deeper didn't have time today will look over the weekend

**Comment by joshstevens19** [comment]
can you try again with the latest i pushed this commit i think the reth provider is holding cache

https://github.com/joshstevens19/reth-indexer/commit/d8f9debd7fef80e0c97e25640c4e9bbcbe5842b4

let me know

**Comment by halljson** [comment]
will have results for you by tomorrow

**Comment by halljson** [comment]
@joshstevens19 most recent commit got this:
```
synced all data to postgres, waiting for new blocks and reth-indexer will now index as they come in.
Elapsed time: 18597.81s
to_block: 18446744073709551615
u64::max: 18446744073709551615
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InitTransaction(11)', src/node_db.rs:66:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by joshstevens19** [comment]
yeah i can recreate moving back to the provider I'm guessing that is holding some cache somewhere trying to work out why

**Comment by joshstevens19** [comment]
ok found the bug was due to the provider i think this commit should do the job i tested my side seem to now keep going when blocks update let me know > https://github.com/joshstevens19/reth-indexer/commit/80c554f3309d3329d23bc7d48dad6163d3a416e1

**Comment by halljson** [comment]
working for me now:
```
synced all data to postgres, waiting for new blocks and reth-indexer will now index as they come in.
Elapsed time: 65.60s
to_block: 18446744073709551615
u64::max: 18446744073709551615
new block(s) found check from: 17708000... last seen: 17707999... latest block: 17708004
new block(s) found check from: 17708005... last seen: 17708004... latest block: 17708005
new block(s) found check from: 17708006... last seen: 17708005... latest block: 17708006
```
db is updating as expected, thank you!

**Comment by joshstevens19** [comment]
Amazing!!!!

**Comment by anishmansuri** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
dabdevelop, @lfarlima, @FlowerWrong, @bubcoco, @otint, @brannondorsey, @JustinLee2018, @colstrom, @luu-alex, @navp4l, @qqpann, @gnbaron, @hhstore, @fayeaa, @scottcheng, @hanpanpan200, @VANITAX, @brbcoding, @leiyin321, @kcskou, @cmanhoff, @thejpanganiban, @drondov, @MarkusGalant, @kdhayal, @donce, @thaerlabs, @roxaxis, @sinao-dev, @davidbancor, @marcogbarcellos, @nazhmik, @JetJadeja, @b68h4, @zhouguanghao, @me-ch, @soohanpark, @xlanex6, @xtools-at, @abans, @brancusi, @GregM, @naltun, @llabori-venehsoftw, @nickmacario, @Brianspha, @kojimaro, @Leo-Mu, @VincentDebug, @keeganmccallum

**Comment by byungster** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
zouguangxian, @majordutch, @humoyun, @PhE, @15659128550, @simonlleeee, @fairhopeweb, @Cedrick320, @BURFAL18, @alighahary, @LeoHChen, @Aarush-Goyal, @s4kibs4mi, @karstengresch, @suliman-nm98, @vynci, @zaicheng-qi, @TB33Z, @Namysh, @chfw, @xinghu, @onepisYa, @gregbyte, @pauloedurezende, @cleanunicorn, @davidkarim, @goggeryang, @saeedkaregar, @woahdy, @KhatiaKrypto, @jack-zhang123, @anyinfa, @std95174, @mikeboiko, @0xDlyan, @shuklaritvik06, @enuoCM, @AngusCool, @funkybase, @grace-mickey405, @nnzo, @malik030, @kuzyakiev, @KXXXXXXXK, @alireza-gsh, @rukmal, @heipacker, @wishfulway, @docongminh, @chamorin
