### ISSUE TITLE
process_block ignores transactions with `to` as none.

### ISSUE THREAD

**Issue by abdullathedruid** [joshstevens19/reth-indexer#32]
I was looking at `indexer.rs` within `process_block` and noticed that transactions were being ignored if the `transaction.to()` is none.

I haven't looked into detail at the whole project, but isn't is possible that contract creation transactions are able to emit events, and therefore these events might get missed by the indexer? 

Thanks for all your work!

**Comment by joshstevens19** [comment]
valid point will fix this

**Comment by joshstevens19** [comment]
https://github.com/joshstevens19/reth-indexer/commit/73362732a1b4944751b8883f1df471bdabc8cfaf
