### ISSUE TITLE
Failed to initialize reth factory: "Could not open database make sure reth node is syncing and readable

### ISSUE THREAD

**Issue by deiay** [joshstevens19/reth-indexer#36]
I'm getting the following error:

```
thread 'main' panicked at 'Failed to initialize reth factory: "Could not open database make sure reth node is syncing and readable"', src/indexer.rs:206:10

[2023-07-18T21:23:59Z ERROR reth_database_reader::provider] Error opening database: Could not open database at path: /ethereum/drive1/share/reth/mainnet/db
```

I'm running a server with two dics:
* On disc 1, I'm running the reth node, postgres, and the indexer on disc 1
* On disc 2 I'm running the db for the reth node  

I've given the indexer access to the db folder, updated the config to point to the folder located in disc 2. It seems that the indexer is having trouble reading the folder location, any ideas what might resolve this?

**Comment by mehranhydary** [comment]
Also interested in this!

**Comment by joshstevens19** [comment]
Hmm sounds like a permission issue; all this is doing is using reth_db lib and passing over the path to connect to the database, it's doing nothing special, so it is either:

1) the path is not correct (unlikely)
2) the process running the indexer has sufficient permissions to access and read the database directory < it is worth checking this as it most likely is a permission issue 

`ls -ld /ethereum/drive1/share/reth/mainnet/db` to see permission may need chmod or chown stuff, also try to ls into that directory from that user also

I am 99% it is a permission thing - sorry i cant help more will leave ticket open let me know what you find

**Comment by joshstevens19** [comment]
Closing as no reply and pretty sure code can’t fix this let me know if we need to reopen 👍
